import uuid
from datetime import datetime, timezone, timedelta
from fastapi import HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.repositories.booking import BookingRepository
from app.repositories.event import EventRepository
from app.schemas.booking import BookingCreate
from app.models.booking import Booking, BookingStatus

class BookingService:
    def __init__(self, db: AsyncSession):
        self.repo = BookingRepository(db)
        self.event_repo = EventRepository(db)

    async def get_user_bookings(self, user_id: uuid.UUID, status: BookingStatus | None = None) -> list[Booking]:
        return await self.repo.get_by_user(user_id, status)

    async def get_bookings_by_event(self, event_id: uuid.UUID) -> list[Booking]:
        return await self.repo.get_by_event(event_id)

    async def get_booking_by_id(self, booking_id: uuid.UUID, current_user_id: uuid.UUID | None = None) -> Booking:
        booking = await self.repo.get(booking_id)
        if not booking:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Booking not found.")
            
        # Optional: verify ownership if current_user_id is passed
        if current_user_id and booking.user_id != current_user_id:
            # We also might want to allow organizers to fetch it, 
            # but usually organizers fetch through event relation
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not authorized to view this booking.")
            
        return booking

    async def create_booking(self, booking_in: BookingCreate, user_id: uuid.UUID) -> Booking:
        # Atomic creation handles the seat deduction and event locking
        try:
            booking = await self.repo.create_booking_atomic(
                event_id=booking_in.event_id,
                user_id=user_id,
                seats=booking_in.number_of_seats
            )
            return booking
        except HTTPException as e:
            # Re-raise HTTP exceptions generated by the repository (e.g. not enough seats)
            raise e
        except Exception as e:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Failed to create booking: {str(e)}"
            )

    async def cancel_booking(self, booking_id: uuid.UUID, user_id: uuid.UUID) -> Booking:
        booking = await self.get_booking_by_id(booking_id, user_id)
        
        if booking.status == BookingStatus.cancelled:
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Booking is already cancelled.")
            
        event = await self.event_repo.get(booking.event_id)
        if not event:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Associated event not found.")
            
        # Business rule: Cannot cancel if event is in the past
        now = datetime.now(timezone.utc).replace(tzinfo=None)
        if event.start_date_time < now:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Cannot cancel booking for a past event."
            )
            
        # Business rule: Cannot cancel within 24 hours of event
        if event.start_date_time - now < timedelta(hours=24):
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Cannot cancel booking within 24 hours of the event start time."
            )
            
        # Restore seats
        update_event_data = {"available_seats": event.available_seats + booking.number_of_seats}
        await self.event_repo.update(event, update_event_data)
        
        # Mark as cancelled
        update_booking_data = {"status": BookingStatus.cancelled}
        return await self.repo.update(booking, update_booking_data)
